### ISSUE TITLE
Is there a plan for pip package?

### ISSUE THREAD

**Issue by skyline75489** [RadeonOpenCompute/rocm_smi_lib#124]
Similar to [nvidia-ml-py](https://pypi.org/project/nvidia-ml-py) that can be used to get detail information about ROCm devices in Python.

**Comment by dmitrii-galantsev** [comment]
There is a plan to replace rocm_smi_lib with [amdsmi](https://github.com/RadeonOpenCompute/amdsmi).  
We are discussing creating a pip package for that.
