### ISSUE TITLE
question: is there a cmdline switch for displaying which apps are using GPU

### ISSUE THREAD

**Issue by jdgh000** [RadeonOpenCompute/rocm_smi_lib#125]
ROCm5.6 / ubuntu 20.04.
I was looking through commands to query current GPU utilization. There appears no commands for which application is using the GPU. As a contrast, nvidia-smi shows it. Is there a similar command available or plan in the future?

**Comment by dmitrii-galantsev** [comment]
Please check out [amdsmi](https://github.com/RadeonOpenCompute/amdsmi)
`amd-smi process` returns the processes :)
![image](https://github.com/RadeonOpenCompute/rocm_smi_lib/assets/19967783/70fbf3c0-1a3f-41f2-bae9-467829a55436)
