### ISSUE TITLE
rocm-smi.py - Function checkIfSecondaryDie is defined twice

### ISSUE THREAD

**Issue by Sabrewarrior** [RadeonOpenCompute/rocm_smi_lib#128]
Second definition was introduced in merge 98baeca615904f782c993b90b9f8ff8545057a34
https://github.com/RadeonOpenCompute/rocm_smi_lib/commit/98baeca615904f782c993b90b9f8ff8545057a34#diff-1bf57333566bfbc368aa56cb127afc34f9ee403eefb0af57980201c68e56e17c

The first definition was fixed in ecb1303732bb0f2859efe1e6eafa4a26ecd0db17 but is not used as the second definition overwrites it.

Causes https://github.com/RadeonOpenCompute/ROCm/issues/2410

**Comment by dmitrii-galantsev** [comment]
That's very odd. I cannot find it in the develop branch. (We just started syncing it! https://github.com/RadeonOpenCompute/rocm_smi_lib/tree/develop)

Something went wrong during merge...

I created a fix internally. It might make it into 6.0 release.

**Comment by dmitrii-galantsev** [comment]
Going to reopen until it's merged.

**Comment by dmitrii-galantsev** [comment]
Still unsure how this keeps making it into releases. Hopefully not present in 6.0...

**Comment by dmitrii-galantsev** [comment]
Ok thank god. It's gone in 6.0
https://github.com/ROCm/rocm_smi_lib/blob/rocm-6.0.0/python_smi_tools/rocm_smi.py#L831
