### ISSUE TITLE
The returned rsmi_status_t is inconsistent 

### ISSUE THREAD

**Issue by effective-qdd** [RadeonOpenCompute/rocm_smi_lib#146]
rocm_smi_lib/src/rocm_smi.cc

In function rsmi_event_notification_mask_set
```
if (dev->evt_notif_anon_fd() == -1) {
    return RSMI_INITIALIZATION_ERROR;
  }
```

And in function rsmi_event_notification_stop(uint32_t dv_ind)
```
if (dev->evt_notif_anon_fd() == -1) {
    return RSMI_STATUS_INVALID_ARGS;
  }
```

Should the returned status also be RSMI_INITIALIZATION_ERROR in `rsmi_event_notification_stop`? 
I'm a little confused when I get RSMI_INITIALIZATION_ERROR because there is only one param (uint32_t 	dv_ind) in the function.

**Comment by ppanchad-amd** [comment]
@effective-qdd Apologies for the lack of response. Do you still need assistance with this ticket? Thanks!

**Comment by harkgill-amd** [comment]
Hi @effective-qdd, the return value under `rsmi_event_notification_stop` is correctly set as `RSMI_STATUS_INVALID_ARGS;`
```
if (dev->evt_notif_anon_fd() == -1) {
    return RSMI_STATUS_INVALID_ARGS;
  }
```
It is set this way as a generic status code for cases that are not initialization based such as if you are trying to stop an event which is already stopped. `rsmi_event_notification_mask_set` on the other hand is one of the first steps done before monitoring events. In this case, the usage of `return RSMI_INITIALIZATION_ERROR;` makes more sense. 

I will close out this issue. If you feel the issue has not been addressed, please leave a comment and I will re-open the issue. Thanks!
