### ISSUE TITLE
rocm_smi.py/amdsmi_cli.py has around a 3 second latency on first call. 

### ISSUE THREAD

**Issue by jw2249a** [RadeonOpenCompute/rocm_smi_lib#151]
This issue wasn't present in 5.7.1, but upon upgrading to 6.0 it has around a 3 second latency. 

It might not be this library specifically, but another upgraded rocm lib. It is just very noticeable here. I built the 5.7.1 version of rocm-smi and it was also noticeably slower with the 6.0 version of the other programs installed. 

Here is the [cprofs](https://github.com/ROCm/rocm_smi_lib/files/13756867/cprofs.zip) documenting the ~3 second latency. Both the amdgpu-install version and compiled version create the same issue. 

The latency goes away if the same query is run again, but if it is changed at all or you wait ~10seconds it becomes slow again. 

I have a 7900 xtx on ubuntu 22.04

**Comment by ppanchad-amd** [comment]
@jw2249a Apologies for the lack of response. Can you please check if issue still exists with the latest ROCm 6.2? If not, please close the ticket. Thanks!
