### ISSUE TITLE
Major device number AMD GPUs

### ISSUE THREAD

**Issue by robzor92** [RadeonOpenCompute/rocm_smi_lib#16]
Hello!

My intention is to build a discovery mechanism using the rocm_smi_lib that queries the system for all available AMD GPUs. I have done similar work for NVIDIA GPUs and in that case I was able to assume the major device number of the GPUs always being 195 since it is reserved by NVIDIA and the minor device number from querying nvml. I see in your library you have _rsmi_dev_id_get_ which from what I understand returns the minor device number, but how can I query for the major device number? Since I need both of them for every AMD GPU present on the system.

Thanks,
Robin

**Comment by fxkamd** [comment]
I believe the minor numbers are for the DRM render node device of each GPU in /dev/dri. AFAIK all DRM devices share the same major number: 226.

**Comment by robzor92** [comment]
Thanks @fxkamd I see https://www.kernel.org/doc/Documentation/admin-guide/devices.txt points me to the same information, I will try it out. Closing for now.
