### ISSUE TITLE
[Feature]: ECC Mode Check

### ISSUE THREAD

**Issue by 842974287** [RadeonOpenCompute/rocm_smi_lib#183]
### Suggestion Description

Hi, for nvidia gpu we can use nvidia-smi to check ECC mode, and use the tool to turn ECC on/off. I couldn't find any documentation on AMD ECC mode. Wondering if rocm-smi also supports checking it for AMD GPUs?

### GPU

MI300x

**Comment by oliveiradan** [comment]
Both `rocm-smi` and `amd-smi` tools can show the ECC status:

- `rocm-smi --showrasinfo`
- `amd-smi monitor --ecc`

The turn on/off setting feature is not available at the moment.

**Comment by sohaibnd** [comment]
@842974287 Closing this issue as it has been answered by @oliveiradan.
