### ISSUE TITLE
logging.warn used instead of logging.warning

### ISSUE THREAD

**Issue by graepaul** [RadeonOpenCompute/rocm_smi_lib#187]
https://github.com/ROCm/rocm_smi_lib/blob/dd954be8876511e1596fad2c6d9d446dd8d5be20/python_smi_tools/rocm_smi.py#L4264

**Comment by ppanchad-amd** [comment]
@graepaul Internal ticket has been created to fix this issue. Thanks!

**Comment by jamesxu2** [comment]
Hi @graepaul, thanks for bringing this up. The change has been internally merged and will be available in a future release.
