### ISSUE TITLE
[Issue]: rocm-smi not setting parameters correctly when on-board gpu is detected

### ISSUE THREAD

**Issue by sdaffe** [RadeonOpenCompute/rocm_smi_lib#207]
### Problem Description

if igpu is enabled it shows up as /sys/class/drm/card0 while rocm-smi does not report this it does however try to write commands to it when it should be writing to /sys/class/drm/card1 when ex. setting a fan on -d 0.. very easy to reproduce if it is intel based igpu. ex. my intel igpu is /sys/class/drm/card0 and rocm-smi detects my amdgpu and displays it as gpu 0.. the problem is rocm send the litteral command to /sys/class/drm/card0 which is intel.

### Operating System

24.04.1 LTS (Noble Numbat)

### CPU

 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz

### GPU

multiple

### ROCm Version

ROCm 6.2.3

### ROCm Component

rocm_smi_lib

**Comment by ppanchad-amd** [comment]
Hi @sdaffe. Internal ticket has been created to investigate your issue. Thanks!

**Comment by tcgu-amd** [comment]
Hi @sdaffe, we recommend [disabling iGPU](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/prerequisites.html#disable-igpu) as a prerequisite to using ROCm to avoid unknown issues. Thanks!

**Comment by tcgu-amd** [comment]
This issue will closed for now. Please feel free to add follow-ups. Thanks!
