### ISSUE TITLE
MCLK question

### ISSUE THREAD

**Issue by jinz2014** [RadeonOpenCompute/rocm_smi_lib#209]
Is the GPU memory bandwidth computed using MCLK on MI300 A ?  It is not clear what the actual maximum memory bandwidth you measured is.  Thank you for explaining it.

![image](https://github.com/user-attachments/assets/2b8cfbe0-5ca1-4a20-bbd0-23316fa259ea)

**Comment by ppanchad-amd** [comment]
Hi @jinz2014. Internal ticket has been created to assist with your question. Thanks!

**Comment by zichguan-amd** [comment]
Hi @jinz2014, `rocm-smi` shows the current GPU metrics, the maximum theoretical bandwidth is calculated using the peak MCLK, which can be obtained with `rocm-smi --showmclkrange`. Example output on MI300As shows peak MCLK is 1300MHz:
```
$ rocm-smi --showmclkrange 


============================ ROCm System Management Interface ============================
================================= Show Valid mclk Range ==================================
GPU[0]          : Valid mclk range: 900Mhz - 1300Mhz
GPU[1]          : Valid mclk range: 900Mhz - 1300Mhz
GPU[2]          : Valid mclk range: 900Mhz - 1300Mhz
GPU[3]          : Valid mclk range: 900Mhz - 1300Mhz
==========================================================================================
================================== End of ROCm SMI Log ===================================
```

**Comment by jinz2014** [comment]
Thanks.
