### ISSUE TITLE
Add lookup for device index given GPU ID

### ISSUE THREAD

**Issue by mlucinhdl** [RadeonOpenCompute/rocm_smi_lib#4]
In order to unambiguously map GPU IDs as reported by **kfd**, please add API call:

    rsmi_status_t rsmi_dev_id_get( uint64_t gpuid, uint32_t* pdv_ind);

Where:

**gpuid** - GPU ID as reported by **kfd** in` /sys/class/kfd/kfd/topology/nodes/<node num>/gpu_id`
**pdv_ind** - pointer to device index (as used throughout rocm_smi_lib APIs)

Return value:

**RSMI_STATUS_SUCCESS** - if OK
**RSMI_STATUS_NOT_SUPPORTED** - if given `gpuid` could not be mapped to device index

**Comment by cfreehill** [comment]
Hi, 
I talked with some people here about this. The gpuid (mentioned above) would not be a reliable way to do this. The way we will probably do it is to construct the PCI identifier, BDFID, and return that for a given device index. So it might look something like this:

rsmi_status_t    rsmi_dev_bdfid_get(uint32_t dv_ind, uint32_t *bdfid)

Then, you could compare that value against the agent property HSA_AMD_AGENT_INFO_BDFID to see if they are the same.

**Comment by cfreehill** [comment]
Latest commit has this change. Please let me know if you see issues. If it looks ok, then please close this issue.

**Comment by mlucinhdl** [comment]
It seems it works. We adjusted one module and are now working on another one which uses rocm_smi. We will close the issue when testing is finished.

**Comment by mlucinhdl** [comment]
This has been fixed.
