### ISSUE TITLE
Python CLI - README.md table

### ISSUE THREAD

**Issue by Maxzor** [RadeonOpenCompute/rocm_smi_lib#90]
Hello, just sharing an itch that I got trying to turn your readme into roff man pages.
The visual tables that you have for setprofile for example do not translate well into roff.
Classic Markdown tables do. I'd probably submit a PR directly.
https://github.com/apjanke/ronn-ng/issues/79

**Comment by dmitrii-galantsev** [comment]
Fixed in https://github.com/RadeonOpenCompute/rocm_smi_lib/commit/275108f5b949f9661d0da65cbe4defaa952c8d28
