### ISSUE TITLE
Does not compile with doc

### ISSUE THREAD

**Issue by Maxzor** [RadeonOpenCompute/rocm_smi_lib#93]
Can compile fine without doc, but with I get:

```
writing tag file...
Running plantuml with JAVA...
lookup cache used 346/65536 hits=1455 misses=358
finished...
[ 45%] Generating latex/refman.pdf
cd /debamd/rocm-smi-lib/rocm-smi-lib/obj-x86_64-linux-gnu/rocm_smi/latex && make > /dev/null
make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[4]: *** [Makefile:8: refman.pdf] Error 1
make[3]: *** [rocm_smi/CMakeFiles/docs.dir/build.make:76: rocm_smi/latex/refman.pdf] Error 2
make[3]: Leaving directory '/debamd/rocm-smi-lib/rocm-smi-lib/obj-x86_64-linux-gnu'
make[2]: *** [CMakeFiles/Makefile2:260: rocm_smi/CMakeFiles/docs.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....

```

**Comment by Maxzor** [comment]
Solved it on debian:bookworm by installing texmaker, instructions not super clear

**Comment by tpkessler** [comment]
Hi! I'm packaging ROCm for Arch Linux and I'm running in the same issue with doxygen 1.9.6 and TeX live 2022.

**Comment by dmitrii-galantsev** [comment]
I submitted a PR internally to update the docs. It's a little messy with https://github.com/RadeonOpenCompute/rocm_smi_lib/tree/docs/5.7.1 somehow running ahead of https://github.com/RadeonOpenCompute/rocm_smi_lib/tree/rocm-5.7.x ...
I expect https://github.com/RadeonOpenCompute/rocm_smi_lib/tree/develop will soon have the best and greatest docs :)
(Dev branch is new! It is synced to the internal staging branch!)

**Comment by dmitrii-galantsev** [comment]
https://github.com/RadeonOpenCompute/rocm_smi_lib/commit/1de63ce5062def48e4cd8ebcd6139ad8e04081dc should fix it. Reopen if you're having issues.
