### ISSUE TITLE
License grant to various README.md and ROCm_SMI_Manual.pdf

### ISSUE THREAD

**Issue by emollier** [RadeonOpenCompute/rocm_smi_lib#97]
Greetings,

While working on _rocm_smi_lib_ packaging into debian, we noted that some of the files were under copyright of AMD but without any explicit reference to the NCSA Open Source License described in _License.txt_, but instead with a disclaimer that "feels" like it would be a problem if we were to redistribute the source code in the context of the debian project:

> [...] No license, including implied or arising by estoppel, to any intellectual property rights is granted by this document. Terms and limitations applicable to the purchase or use of AMD’s products are as set forth in a signed agreement between the parties or in AMD's Standard Terms and Conditions of Sale.
>
> © 2020 Advanced Micro Devices, Inc. All Rights Reserved.

These files are:
  * README.md
  * python_smi_tools/README.md
  * rocm_smi/docs/ROCm_SMI_Manual.pdf

If these files are actually redistributable per NCSA license, would it be possible to indicate it explicitly alongside the disclaimer?  Otherwise I believe I must assume I cannot redistribute them.

In any case, many thanks for making available ROCm source code!

Have a nice day,  :)
Étienne.

PS: I am not a native English speaker, so don't hesitate to let me know if I misinterpreted the disclaimer for a legally binding statement or misunderstood it entirely.

**Comment by kentrussell** [comment]
Thanks for raising this issue, Etienne. We are discussing it internally and intend to adjust the language accordingly (hopefully in our next ROCm release). It definitely raises questions, so we're happy to get this cleaned up to avoid any confusion in the future.

**Comment by emollier** [comment]
Hi Kent,

I see the redistribution issue [looks addressed](https://github.com/RadeonOpenCompute/rocm_smi_lib/commit/b17b3b2196ba26e63ff3a2b3121cd99f82b0ff56) in ROCm 5.1.

Thank you very much,  :)
Étienne.

**Comment by emollier** [comment]
Hi Kent,

_rocm_smi_lib_ has been accepted after review (including copyright items) in debian unstable.  I close the issue.

Thanks again!
Étienne.
